# Название приложения
spring.application.name=geo-server

# Подключение к PostgreSQL 16 
spring.datasource.url=jdbc:postgresql://localhost:5431/geo_app
spring.datasource.username=admin
spring.datasource.password=secret123
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update          
spring.jpa.show-sql=true                      
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Порт сервера 
server.port=8081

# Настройки JWT 
jwt.secret=VGhpc0lzQVN1cGVyTG9uZ1NlY3JldEtlRm9ySlhUQnJvamVjdEdob3N0QQ==
jwt.expiration=86400000                       

# Дополнительно: отключаем предупреждение open-in-view 
spring.jpa.open-in-view=false